conduit/data/datamodules/__init__.py, conduit/data/datamodules/audio/__init__.py, conduit/data/datamodules/audio/base.py, conduit/data/datamodules/audio/ecoacoustics.py, conduit/data/datamodules/base.py, conduit/data/datasets/audio/base.py, conduit/data/datasets/audio/ecoacoustics.py, conduit/types.py, tests/data_test.py
=> Implement datamodule for ecoacoustics dataset

conduit/data/datasets/audio/ecoacoustics.py, conduit/data/datasets/utils.py, poetry.lock, pyproject.toml
Pin torch/torchvision/torchaudio versions.
=> Merge with-jar extracting code with download_from_url and pin versions of torch-related dependencies.

.github/workflows/ci.yml
=> Run slow tests for weekly test

conduit/data/datamodules/vision/__init__.py, conduit/data/datamodules/vision/camelyon17.py, conduit/data/datamodules/vision/dummy.py, conduit/data/datamodules/vision/nico.py, conduit/data/datasets/camelyon17.py, conduit/data/datasets/utils.py, conduit/data/datasets/vision/__init__.py, conduit/data/datasets/vision/camelyon17.py, conduit/data/datasets/vision/waterbirds.py, conduit/data/structures.py
- Adapt Camelyon17 dataset from WILDS.
- Add ``__iter__`` methods to Sample classes to allow for unpacking.
=> camelyon17

conduit/data/datamodules/base.py, conduit/data/datamodules/vision/base.py, conduit/data/datamodules/vision/camelyon17.py, conduit/data/datamodules/vision/celeba.py, conduit/data/datamodules/vision/cmnist.py, conduit/data/datamodules/vision/dummy.py, conduit/data/datamodules/vision/nico.py, conduit/data/datamodules/vision/waterbirds.py, conduit/data/datasets/audio/base.py, conduit/data/datasets/base.py, conduit/data/datasets/utils.py, conduit/data/datasets/vision/base.py, conduit/data/datasets/vision/cmnist.py, conduit/data/datasets/wrappers.py, conduit/data/structures.py, conduit/fair/metrics/accuracy_per_sens.py
Improve generic-typing of datasets.
=> Add magic methods, improve generic-typing, and other things.

conduit/architectures/vit.py, conduit/data/datamodules/audio/base.py, conduit/data/datamodules/base.py, conduit/data/datamodules/vision/base.py, conduit/data/datasets/base.py, conduit/data/datasets/utils.py, conduit/data/datasets/wrappers.py, conduit/data/structures.py, conduit/models/erm.py, conduit/models/self_supervised/base.py, conduit/models/self_supervised/callbacks.py, conduit/models/self_supervised/moco/v2/lightning.py
Add converter attribute to cdt_collate.
=> Add SizedDataset protocol and replace uses of DatasetProt with it appopriately.

poetry.lock, pyproject.toml
We can't go higher because conduit wants to be compatible with python 3.10, but EthicML cannot be because ray isn't compatible with that, and I didn't backport the joblib change to the EthicML main branch.
=> Update EthicML to at least 0.5.0

make_release.sh, pyproject.toml
=> Bump version for new release

pyproject.toml
=> release 0.1.1

make_release.sh
I don't know why I didn't think of this earlier.
=> Release script: auto-merge the PR

pyproject.toml
=> release 0.1.2

pyproject.toml
=> release 0.1.3

poetry.lock, pyproject.toml
No point in constraining a dependency that's not used anymore.
=> remove unneccessary dependency

conduit/data/datamodules/vision/base.py
After this fix:
```
(Pdb) batch.x.mean()
tensor(-0.0608, device='cuda:0')
(Pdb) batch.x.std()
tensor(1.2612, device='cuda:0')
```
=> Set `max_pixel_value` to 1.0 in `Normalize`

pyproject.toml
=> release 0.1.5

pyproject.toml
=> release 0.1.6

conduit/metrics.py, tests/metrics_test.py
Use init instead of partial to assign function values to Aggregator enum.
Add more classification metrics and expand metrics test.
=> Set exclude_self in reduce_scatter to False to correct 1-off error.

.yamllint.yaml, conduit/data/datasets/vision/camelyon17.py, conduit/data/datasets/vision/celeba.py, conduit/data/datasets/vision/isic.py, conduit/data/datasets/vision/nico.py, conduit/data/datasets/vision/nih.py, conduit/data/datasets/vision/pacs.py, conduit/data/datasets/vision/ssrp.py, conduit/data/datasets/vision/waterbirds.py
=> Fix errors introduced by conversion to StrEnum.

conduit/metrics.py, tests/metrics_test.py
- Make fscore robust to disjointness.
- Shore up metric tests.
=> Make `fscore` robust to disjointness in the predicted and target labels.

pyproject.toml
=> Version bump v0.2.0

pyproject.toml
=> Version bump v0.2.1

conduit/data/datamodules/audio/ecoacoustics.py, conduit/data/datamodules/vision/__init__.py, conduit/data/datamodules/vision/nico_plus_plus.py, conduit/data/datasets/audio/ecoacoustics.py, conduit/data/datasets/utils.py, conduit/data/datasets/vision/__init__.py, conduit/data/datasets/vision/nico_plus_plus.py, conduit/data/structures.py, conduit/metrics.py, pyproject.toml
This is mostly a copy of the NICI code, but with the special
train_props.
=> Add the NICO++ dataset

pyproject.toml
=> Version bump v0.3.0

pyproject.toml
=> Version bump v0.3.3

pyproject.toml
=> Version bump v0.3.4

conduit/data/datamodules/base.py, conduit/data/datasets/base.py, conduit/data/datasets/utils.py, conduit/data/datasets/vision/base.py, conduit/data/datasets/vision/pacs.py, conduit/data/datasets/wrappers.py, conduit/data/structures.py, conduit/transforms/multicrop.py, tests/data_test.py
This wasn't checked by pyright.
=> Fix methods that override an overload

pyproject.toml
=> Version bump v0.3.5

conduit/data/datamodules/base.py, conduit/data/datamodules/vision/base.py, conduit/data/datamodules/vision/celeba.py, conduit/data/datamodules/vision/cmnist.py, conduit/data/datasets/utils.py, conduit/data/datasets/vision/isic.py, conduit/data/datasets/wrappers.py, conduit/fair/data/datasets/acs.py, conduit/transforms/multicrop.py, pyproject.toml, typings/folktables/acs.pyi, typings/folktables/folktables.pyi
Otherwise we can't use ruff as a formatter.
=> Change line length for imports

pyproject.toml
=> Version bump v0.4.0

conduit/metrics.py, tests/metrics_test.py
=> Add more metrics

pyproject.toml
=> Version bump v0.4.2
